# Generated by Django 5.0.7 on 2026-06-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '菜品分类',
                'verbose_name_plural': '菜品分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='菜品名称')),
                ('description', models.TextField(blank=True, verbose_name='菜品介绍')),
                ('image_url', models.URLField(blank=True, verbose_name='图片地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('meal_period', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐')], max_length=20, verbose_name='供餐时段')),
                ('available_date', models.DateField(verbose_name='供应日期')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='热量(kcal)')),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='蛋白质(g)')),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='脂肪(g)')),
                ('carbohydrate', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='碳水(g)')),
                ('sodium', models.PositiveIntegerField(default=0, verbose_name='钠(mg)')),
                ('allergens', models.CharField(blank=True, max_length=160, verbose_name='过敏原')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'ordering': ['available_date', 'meal_period', 'category__sort_order', 'name'],
            },
        ),
    ]
