# Generated by Django 5.0.7 on 2026-06-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=50, verbose_name='配送员')),
                ('courier_phone', models.CharField(blank=True, max_length=30, verbose_name='配送电话')),
                ('route', models.CharField(blank=True, max_length=160, verbose_name='配送路线')),
                ('status', models.CharField(choices=[('waiting', '待分配'), ('assigned', '已分配'), ('picked', '已取餐'), ('delivered', '已送达'), ('failed', '异常')], default='waiting', max_length=20, verbose_name='配送状态')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='预计送达')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='实际送达')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': '配送任务',
                'verbose_name_plural': '配送任务',
                'ordering': ['status', 'estimated_arrival'],
            },
        ),
    ]
