# Generated by Django 5.0.7 on 2026-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='方案名称')),
                ('calorie_min', models.PositiveIntegerField(verbose_name='最低热量')),
                ('calorie_max', models.PositiveIntegerField(verbose_name='最高热量')),
                ('protein_min', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='最低蛋白质')),
                ('sodium_max', models.PositiveIntegerField(verbose_name='最高钠')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='提示')),
            ],
            options={
                'verbose_name': '营养方案',
                'verbose_name_plural': '营养方案',
            },
        ),
    ]
